import {
  User,
  Lead,
  Client,
  Project,
  Task,
  Proposal,
  Invoice,
  Activity,
  TimeLog,
  AuditLog,
  WebhookLog,
} from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'u-1',
    name: 'Sarah Jenkins',
    email: 'sarah@digitalx.io',
    role: 'ADMIN',
    department: 'Executive / Founder',
    phone: '+61 400 123 888',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    startDate: '2022-01-15',
    skills: ['Agency Leadership', 'AI Architecture', 'Enterprise Sales', 'Strategy'],
    certifications: ['AWS Certified Solutions Architect', 'GHL Master Certified'],
    experienceNotes: '10+ years scaling digital agencies in Sydney & USA. Formerly Head of Growth at TechX.',
    cvUrl: '/docs/resume-sarah-jenkins.pdf',
    rating: 5.0,
    workloadLevel: 'HIGH',
  },
  {
    id: 'u-2',
    name: 'Alex Rivera',
    email: 'alex@digitalx.io',
    role: 'MEMBER',
    department: 'AI Engineering',
    phone: '+61 412 987 654',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    startDate: '2023-03-01',
    skills: ['Twilio / Vapi', 'Python / Node.js', 'LLM Prompt Engineering', 'LangChain'],
    certifications: ['Vapi AI Voice Specialist', 'OpenAI API Certification'],
    experienceNotes: 'Built 40+ AI voice agents for healthcare and automotive call centers.',
    cvUrl: '/docs/resume-alex-rivera.pdf',
    rating: 4.9,
    workloadLevel: 'HIGH',
  },
  {
    id: 'u-3',
    name: 'Marcus Vance',
    email: 'marcus@digitalx.io',
    role: 'MEMBER',
    department: 'Automation & Integration',
    phone: '+61 423 111 222',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    startDate: '2023-06-15',
    skills: ['n8n Workflow Mastery', 'REST API Design', 'Webhooks', 'Make.com'],
    certifications: ['n8n Expert Partner', 'Zapier Master'],
    experienceNotes: 'Automated 200+ enterprise workflows saving 5,000+ hours annually.',
    cvUrl: '/docs/resume-marcus-vance.pdf',
    rating: 4.8,
    workloadLevel: 'MEDIUM',
  },
  {
    id: 'u-4',
    name: 'Elena Rostova',
    email: 'elena@digitalx.io',
    role: 'MEMBER',
    department: 'CRM & Funnels',
    phone: '+61 434 555 777',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    startDate: '2023-08-10',
    skills: ['GoHighLevel CRM', 'Missed-Call Text-Back', 'SMS Sequences', 'Funnels'],
    certifications: ['GoHighLevel Platinum Admin'],
    experienceNotes: 'Specializes in high-converting SaaS CRM architecture for Home Services.',
    cvUrl: '/docs/resume-elena-rostova.pdf',
    rating: 4.9,
    workloadLevel: 'HIGH',
  },
  {
    id: 'u-5',
    name: 'Chloe Bennett',
    email: 'chloe@digitalx.io',
    role: 'MEMBER',
    department: 'Paid Media & Growth',
    phone: '+61 445 888 999',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    startDate: '2023-11-20',
    skills: ['Meta Ads Manager', 'Conversion Tracking', 'Lead Capture Funnels', 'GA4'],
    certifications: ['Meta Certified Media Buying Professional'],
    experienceNotes: 'Managed over $2.5M in ad spend across AU and US local business markets.',
    cvUrl: '/docs/resume-chloe-bennett.pdf',
    rating: 4.7,
    workloadLevel: 'MEDIUM',
  },
  {
    id: 'u-6',
    name: 'Liam Patel',
    email: 'liam@digitalx.io',
    role: 'MEMBER',
    department: 'Client Success',
    phone: '+61 456 222 333',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    startDate: '2024-01-10',
    skills: ['Client Onboarding', 'Retainer Management', 'Account Retention', 'NPS'],
    certifications: ['Certified Customer Success Manager (CCSM)'],
    experienceNotes: 'Maintains 96% client retention rate across all DigitalX recurring accounts.',
    cvUrl: '/docs/resume-liam-patel.pdf',
    rating: 4.9,
    workloadLevel: 'LOW',
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'l-101',
    name: 'Sydney Roofing Experts',
    company: 'Sydney Roofing Experts Pty Ltd',
    email: 'contact@sydneyroofing.com.au',
    phone: '+61 2 9876 5432',
    source: 'Meta Ads',
    vertical: 'Home Services',
    country: 'AU',
    status: 'WON',
    score: 92,
    ownerId: 'u-4',
    ownerName: 'Elena Rostova',
    notes: 'Urgent need for AI missed-call text-back and GHL pipeline setup. Won contract for $5.5k setup + $2.2k/mo.',
    tags: ['High Intent', 'Emergency Call-Out', 'Sydney CBD'],
    followUpDate: '2026-07-25',
    createdAt: '2026-07-01',
  },
  {
    id: 'l-102',
    name: 'LA Dental Care Group',
    company: 'LA Dental Care Inc',
    email: 'admin@ladentalcare.com',
    phone: '+1 310 555 0199',
    source: 'Apollo.io',
    vertical: 'Healthcare',
    country: 'US',
    status: 'WON',
    score: 95,
    ownerId: 'u-2',
    ownerName: 'Alex Rivera',
    notes: 'Wanted 24/7 AI Voice reception agent for after-hours patient appointment booking. Won contract.',
    tags: ['Enterprise', 'AI Voice Agent', 'Los Angeles'],
    followUpDate: '2026-07-28',
    createdAt: '2026-07-02',
  },
  {
    id: 'l-103',
    name: 'Melbourne Prestige Motors',
    company: 'Prestige Motors Group AU',
    email: 'sales@prestigemotors.com.au',
    phone: '+61 3 9123 4567',
    source: 'GoHighLevel',
    vertical: 'Automotive',
    country: 'AU',
    status: 'NEGOTIATION',
    score: 85,
    ownerId: 'u-1',
    ownerName: 'Sarah Jenkins',
    notes: 'Negotiating custom n8n lead sync with inventory database + Meta Ads lead capture.',
    tags: ['Automotive', 'High Value Retainer'],
    followUpDate: '2026-07-22',
    createdAt: '2026-07-05',
  },
  {
    id: 'l-104',
    name: 'Bondi Spa & Wellness',
    company: 'Bondi Beauty Haven',
    email: 'info@bondispa.com.au',
    phone: '+61 2 9300 4455',
    source: 'Website Form',
    vertical: 'Beauty & Wellness',
    country: 'AU',
    status: 'WON',
    score: 90,
    ownerId: 'u-6',
    ownerName: 'Liam Patel',
    notes: 'Needs online booking chatbot + automated SMS review generation funnel.',
    tags: ['Bondi Beach', 'SMS Marketing'],
    followUpDate: '2026-07-24',
    createdAt: '2026-07-08',
  },
  {
    id: 'l-105',
    name: 'Austin Legal Advisory',
    company: 'Austin Legal Partners LLP',
    email: 'partners@austinlegal.com',
    phone: '+1 512 555 8822',
    source: 'Apollo.io',
    vertical: 'Professional Services',
    country: 'US',
    status: 'PROPOSAL_SENT',
    score: 78,
    ownerId: 'u-5',
    ownerName: 'Chloe Bennett',
    notes: 'Proposal sent for Meta Ads lead generation + GHL intake automation ($4k setup, $3k/mo retainer).',
    tags: ['Legal Tech', 'Texas Market'],
    followUpDate: '2026-07-23',
    createdAt: '2026-07-10',
  },
  {
    id: 'l-106',
    name: 'Brisbane Steakhouse & Lounge',
    company: 'Brisbane Hospitality Group',
    email: 'events@brisbanesteakhouse.com.au',
    phone: '+61 7 3222 1100',
    source: 'Referral',
    vertical: 'Hospitality',
    country: 'AU',
    status: 'WON',
    score: 88,
    ownerId: 'u-3',
    ownerName: 'Marcus Vance',
    notes: 'VIP table reservation AI voice agent + n8n calendar sync.',
    tags: ['VIP Client', 'Brisbane CBD'],
    followUpDate: '2026-07-29',
    createdAt: '2026-07-11',
  },
  {
    id: 'l-107',
    name: 'Harbor Lights Resort Sydney',
    company: 'Harbor Hospitality Group',
    email: 'gm@harborlightsresort.com.au',
    phone: '+61 2 9555 0011',
    source: 'Website Form',
    vertical: 'Hospitality',
    country: 'AU',
    status: 'LOST',
    score: 45,
    ownerId: 'u-1',
    ownerName: 'Sarah Jenkins',
    notes: 'Decided to postpone automation project until Q4 due to internal restructuring.',
    tags: ['Budget Postponed'],
    followUpDate: '2026-10-01',
    createdAt: '2026-06-15',
  },
  {
    id: 'l-108',
    name: 'California Solar Solutions',
    company: 'CA Solar Pros Inc',
    email: 'leads@casolarpros.com',
    phone: '+1 415 555 7711',
    source: 'Meta Ads',
    vertical: 'Home Services',
    country: 'US',
    status: 'QUALIFIED',
    score: 82,
    ownerId: 'u-2',
    ownerName: 'Alex Rivera',
    notes: 'Qualifying lead for AI solar quote voice assistant. Target demo scheduled.',
    tags: ['Renewable Energy', 'AI Voice Assistant'],
    followUpDate: '2026-07-24',
    createdAt: '2026-07-14',
  },
  {
    id: 'l-109',
    name: 'Apex Wealth Management AU',
    company: 'Apex Financial Services Ltd',
    email: 'wealth@apexwealth.com.au',
    phone: '+61 2 8200 9988',
    source: 'Referral',
    vertical: 'Professional Services',
    country: 'AU',
    status: 'WON',
    score: 96,
    ownerId: 'u-3',
    ownerName: 'Marcus Vance',
    notes: 'Compliance-approved n8n database integration and client intake bot. Won $12.5k setup + $5.5k/mo retainer.',
    tags: ['Enterprise Finance', 'High Value'],
    followUpDate: '2026-07-26',
    createdAt: '2026-07-12',
  },
  {
    id: 'l-110',
    name: 'Gold Coast Fitness Hub',
    company: 'Gold Coast Gyms Group',
    email: 'info@gcfitnesshub.com.au',
    phone: '+61 7 5511 2233',
    source: 'GoHighLevel',
    vertical: 'Beauty & Wellness',
    country: 'AU',
    status: 'CONTACTED',
    score: 65,
    ownerId: 'u-5',
    ownerName: 'Chloe Bennett',
    notes: 'Initial contact made. Interested in Meta ads funnel for trial member signups.',
    tags: ['Fitness', 'Gold Coast'],
    followUpDate: '2026-07-22',
    createdAt: '2026-07-16',
  },
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'c-201',
    leadId: 'l-101',
    companyName: 'Sydney Roofing Experts',
    primaryContact: 'Dave Thompson (Managing Director)',
    email: 'dave@sydneyroofing.com.au',
    phone: '+61 2 9876 5432',
    vertical: 'Home Services',
    country: 'AU',
    status: 'ACTIVE',
    servicesSold: ['Missed-Call Text-Back', 'GoHighLevel Setup', 'n8n Automation'],
    setupFee: 5500,
    monthlyRetainer: 2200,
    contractStartDate: '2026-07-05',
    lifetimeRevenue: 7700,
    onboardingChecklist: [
      { id: 'ob-1', task: 'Receive GHL admin access & Twilio numbers', done: true },
      { id: 'ob-2', task: 'Configure missed-call text-back triggers', done: true },
      { id: 'ob-3', task: 'Test emergency call routing webhook', done: true },
      { id: 'ob-4', task: 'Staff training video delivery', done: false },
    ],
    createdAt: '2026-07-05',
  },
  {
    id: 'c-202',
    leadId: 'l-102',
    companyName: 'LA Dental Care Group',
    primaryContact: 'Dr. Robert Chen (Chief Medical Officer)',
    email: 'drchen@ladentalcare.com',
    phone: '+1 310 555 0199',
    vertical: 'Healthcare',
    country: 'US',
    status: 'ACTIVE',
    servicesSold: ['AI Voice Agents', 'GoHighLevel Setup', 'Analytics Dashboard'],
    setupFee: 8500,
    monthlyRetainer: 3500,
    contractStartDate: '2026-07-08',
    lifetimeRevenue: 12000,
    onboardingChecklist: [
      { id: 'ob-1', task: 'HIPAA compliance agreement signed', done: true },
      { id: 'ob-2', task: 'AI voice agent prompt engineering', done: true },
      { id: 'ob-3', task: 'EHR calendar API integration', done: false },
    ],
    createdAt: '2026-07-08',
  },
  {
    id: 'c-203',
    leadId: 'l-104',
    companyName: 'Bondi Spa & Wellness',
    primaryContact: 'Sophia Martinez (Founder)',
    email: 'sophia@bondispa.com.au',
    phone: '+61 2 9300 4455',
    vertical: 'Beauty & Wellness',
    country: 'AU',
    status: 'ACTIVE',
    servicesSold: ['Chatbots', 'Meta Ads', 'Missed-Call Text-Back'],
    setupFee: 4200,
    monthlyRetainer: 1800,
    contractStartDate: '2026-07-10',
    lifetimeRevenue: 6000,
    onboardingChecklist: [
      { id: 'ob-1', task: 'Instagram & WhatsApp chatbot active', done: true },
      { id: 'ob-2', task: 'Meta Ad accounts connected', done: true },
    ],
    createdAt: '2026-07-10',
  },
  {
    id: 'c-204',
    leadId: 'l-106',
    companyName: 'Brisbane Steakhouse & Lounge',
    primaryContact: 'Michael O’Connor (General Manager)',
    email: 'michael@brisbanesteakhouse.com.au',
    phone: '+61 7 3222 1100',
    vertical: 'Hospitality',
    country: 'AU',
    status: 'ACTIVE',
    servicesSold: ['AI Voice Agents', 'n8n Automation', 'Web Design'],
    setupFee: 6500,
    monthlyRetainer: 2500,
    contractStartDate: '2026-07-14',
    lifetimeRevenue: 9000,
    onboardingChecklist: [
      { id: 'ob-1', task: 'Table booking voice bot testing', done: true },
      { id: 'ob-2', task: 'OpenTable API integration', done: true },
    ],
    createdAt: '2026-07-14',
  },
  {
    id: 'c-205',
    leadId: 'l-109',
    companyName: 'Apex Wealth Management AU',
    primaryContact: 'Harrison Vance (Partner)',
    email: 'hvance@apexwealth.com.au',
    phone: '+61 2 8200 9988',
    vertical: 'Professional Services',
    country: 'AU',
    status: 'ACTIVE',
    servicesSold: ['n8n Automation', 'GoHighLevel Setup', 'Analytics Dashboard', 'AI Voice Agents'],
    setupFee: 12500,
    monthlyRetainer: 5500,
    contractStartDate: '2026-07-15',
    lifetimeRevenue: 18000,
    onboardingChecklist: [
      { id: 'ob-1', task: 'Security & compliance audit', done: true },
      { id: 'ob-2', task: 'n8n private server deployment', done: true },
      { id: 'ob-3', task: 'Executive dashboard launch', done: true },
    ],
    createdAt: '2026-07-15',
  },

  // Churned / Past Clients
  {
    id: 'c-301',
    companyName: 'Melbourne Auto Repairs',
    primaryContact: 'Gary Smith',
    email: 'gary@melbourneautorepairs.com.au',
    phone: '+61 3 9444 3322',
    vertical: 'Automotive',
    country: 'AU',
    status: 'CHURNED',
    servicesSold: ['Missed-Call Text-Back', 'Meta Ads'],
    setupFee: 3500,
    monthlyRetainer: 1500,
    contractStartDate: '2025-06-01',
    exitDate: '2026-05-31',
    churnReason: 'Business sold to a national conglomerate who had internal IT team.',
    lifetimeRevenue: 21500,
    reactivationNotes: 'Contact new owner in Q4 2026 when national IT contract expires.',
    onboardingChecklist: [],
    createdAt: '2025-06-01',
  },
  {
    id: 'c-302',
    companyName: 'Sydney Coastal Cafe',
    primaryContact: 'Claire Williams',
    email: 'claire@sydneycoastal.com.au',
    phone: '+61 2 9111 8877',
    vertical: 'Hospitality',
    country: 'AU',
    status: 'CHURNED',
    servicesSold: ['Chatbots'],
    setupFee: 2500,
    monthlyRetainer: 1000,
    contractStartDate: '2025-08-15',
    exitDate: '2026-04-15',
    churnReason: 'Seasonal budget reduction during winter.',
    lifetimeRevenue: 10500,
    reactivationNotes: 'High likelihood of reactivation prior to summer (October 2026).',
    onboardingChecklist: [],
    createdAt: '2025-08-15',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'p-401',
    clientId: 'c-202',
    clientName: 'LA Dental Care Group',
    name: 'AI Voice Receptionist Rollout',
    serviceType: 'AI Voice Agents',
    status: 'IN_PROGRESS',
    targetDelivery: '2026-08-10',
    assignees: ['Alex Rivera', 'Marcus Vance'],
    tasksCount: 6,
    completedTasksCount: 4,
    createdAt: '2026-07-09',
  },
  {
    id: 'p-402',
    clientId: 'c-201',
    clientName: 'Sydney Roofing Experts',
    name: 'GHL Emergency Call Pipeline',
    serviceType: 'GoHighLevel Setup',
    status: 'IN_PROGRESS',
    targetDelivery: '2026-07-30',
    assignees: ['Elena Rostova'],
    tasksCount: 4,
    completedTasksCount: 3,
    createdAt: '2026-07-06',
  },
  {
    id: 'p-403',
    clientId: 'c-203',
    clientName: 'Bondi Spa & Wellness',
    name: 'Instagram & Review Chatbot Funnel',
    serviceType: 'Chatbots',
    status: 'COMPLETED',
    completionDate: '2026-07-18',
    finalInvoiceValue: 4200,
    csatRating: 5,
    testimonialQuote: 'DigitalX completely automated our booking workflow. We got 47 new review submissions in our first week alone!',
    assignees: ['Elena Rostova', 'Chloe Bennett'],
    tasksCount: 5,
    completedTasksCount: 5,
    createdAt: '2026-07-10',
  },
  {
    id: 'p-404',
    clientId: 'c-205',
    clientName: 'Apex Wealth Management AU',
    name: 'Enterprise n8n Sync Engine',
    serviceType: 'n8n Automation',
    status: 'IN_PROGRESS',
    targetDelivery: '2026-08-15',
    assignees: ['Marcus Vance', 'Sarah Jenkins'],
    tasksCount: 8,
    completedTasksCount: 5,
    createdAt: '2026-07-16',
  },
  {
    id: 'p-405',
    clientId: 'c-204',
    clientName: 'Brisbane Steakhouse & Lounge',
    name: 'VIP Reservation Voice Agent',
    serviceType: 'AI Voice Agents',
    status: 'COMPLETED',
    completionDate: '2026-07-19',
    finalInvoiceValue: 6500,
    csatRating: 5,
    testimonialQuote: 'Our phone reservations are now answered 100% of the time, even during peak Friday dinner service.',
    assignees: ['Alex Rivera'],
    tasksCount: 4,
    completedTasksCount: 4,
    createdAt: '2026-07-14',
  },

  // Pending Projects
  {
    id: 'p-406',
    clientId: 'c-201',
    clientName: 'Sydney Roofing Experts',
    name: 'Phase 2: Meta Ads Lead Automation',
    serviceType: 'Meta Ads',
    status: 'PENDING',
    targetDelivery: '2026-08-25',
    expectedStartDate: '2026-08-01',
    blockerNotes: 'Waiting on client to approve final ad copy & creative assets package.',
    delayReason: 'Client internal marketing director on annual leave until July 28.',
    assignees: ['Chloe Bennett'],
    tasksCount: 4,
    completedTasksCount: 0,
    createdAt: '2026-07-15',
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 't-501',
    projectId: 'p-401',
    projectName: 'AI Voice Receptionist Rollout',
    clientId: 'c-202',
    clientName: 'LA Dental Care Group',
    title: 'Configure Vapi voice latency thresholds (<500ms)',
    priority: 'URGENT',
    status: 'IN_PROGRESS',
    dueDate: '2026-07-22',
    assignedTo: 'Alex Rivera',
    assignedId: 'u-2',
    estimatedHours: 4.0,
    loggedHours: 3.5,
    createdAt: '2026-07-19',
  },
  {
    id: 't-502',
    projectId: 'p-402',
    projectName: 'GHL Emergency Call Pipeline',
    clientId: 'c-201',
    clientName: 'Sydney Roofing Experts',
    title: 'Setup Twilio Missed-Call Webhook to GHL Workflow',
    priority: 'HIGH',
    status: 'DONE',
    dueDate: '2026-07-18',
    assignedTo: 'Elena Rostova',
    assignedId: 'u-4',
    estimatedHours: 3.0,
    loggedHours: 3.0,
    createdAt: '2026-07-16',
  },
  {
    id: 't-503',
    projectId: 'p-404',
    projectName: 'Enterprise n8n Sync Engine',
    clientId: 'c-205',
    clientName: 'Apex Wealth Management AU',
    title: 'Implement AES-256 encryption for stored API tokens in n8n',
    priority: 'URGENT',
    status: 'IN_PROGRESS',
    dueDate: '2026-07-23',
    assignedTo: 'Marcus Vance',
    assignedId: 'u-3',
    estimatedHours: 6.0,
    loggedHours: 4.0,
    createdAt: '2026-07-20',
  },
  {
    id: 't-504',
    projectId: 'p-401',
    projectName: 'AI Voice Receptionist Rollout',
    clientId: 'c-202',
    clientName: 'LA Dental Care Group',
    title: 'EHR Dental Calendar API Sandbox Testing',
    priority: 'HIGH',
    status: 'TODO',
    dueDate: '2026-07-25',
    assignedTo: 'Alex Rivera',
    assignedId: 'u-2',
    estimatedHours: 8.0,
    loggedHours: 0.0,
    createdAt: '2026-07-20',
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-601',
    invoiceNumber: 'INV-2026-001',
    clientId: 'c-205',
    clientName: 'Apex Wealth Management AU',
    amount: 12500,
    type: 'SETUP_FEE',
    issueDate: '2026-07-15',
    dueDate: '2026-07-22',
    status: 'PAID',
    paidDate: '2026-07-16',
  },
  {
    id: 'inv-602',
    invoiceNumber: 'INV-2026-002',
    clientId: 'c-202',
    clientName: 'LA Dental Care Group',
    amount: 8500,
    type: 'SETUP_FEE',
    issueDate: '2026-07-08',
    dueDate: '2026-07-22',
    status: 'PAID',
    paidDate: '2026-07-12',
  },
  {
    id: 'inv-603',
    invoiceNumber: 'INV-2026-003',
    clientId: 'c-202',
    clientName: 'LA Dental Care Group',
    amount: 3500,
    type: 'MONTHLY_RETAINER',
    issueDate: '2026-07-15',
    dueDate: '2026-07-29',
    status: 'UNPAID',
  },
  {
    id: 'inv-604',
    invoiceNumber: 'INV-2026-004',
    clientId: 'c-201',
    clientName: 'Sydney Roofing Experts',
    amount: 2200,
    type: 'MONTHLY_RETAINER',
    issueDate: '2026-07-01',
    dueDate: '2026-07-15',
    status: 'OVERDUE',
  },
  {
    id: 'inv-605',
    invoiceNumber: 'INV-2026-005',
    clientId: 'c-204',
    clientName: 'Brisbane Steakhouse & Lounge',
    amount: 6500,
    type: 'SETUP_FEE',
    issueDate: '2026-07-14',
    dueDate: '2026-07-28',
    status: 'PAID',
    paidDate: '2026-07-19',
  },
];

export const INITIAL_PROPOSALS: Proposal[] = [
  {
    id: 'prop-701',
    clientId: 'c-202',
    clientName: 'LA Dental Care Group',
    title: 'AI Voice Receptionist & Patient Booking Engine',
    version: 'v1.2',
    status: 'ACCEPTED',
    totalValue: 12000,
    sentDate: '2026-07-05',
    eSigned: true,
    eSignatureData: 'Dr. Robert Chen [Signed 2026-07-07]',
    phases: [
      { phaseName: 'Phase 1: Voice Bot Persona & Twilio Setup', scope: 'Prompt design, call routing & custom voice synthesis', timeline: '1 week', cost: 4500 },
      { phaseName: 'Phase 2: EHR Calendar & EHR Webhook Integration', scope: 'Live appointment slot lookup & patient record sync', timeline: '2 weeks', cost: 4000 },
      { phaseName: 'Phase 3: Monthly Support & Retainer', scope: 'Ongoing latency optimization, 99.9% SLA & updates', timeline: 'Monthly', cost: 3500 },
    ],
    createdAt: '2026-07-04',
  },
  {
    id: 'prop-702',
    clientId: 'c-205',
    clientName: 'Apex Wealth Management AU',
    title: 'Enterprise n8n Workflow Architecture & Security Audit',
    version: 'v2.0',
    status: 'ACCEPTED',
    totalValue: 18000,
    sentDate: '2026-07-11',
    eSigned: true,
    eSignatureData: 'Harrison Vance [Signed 2026-07-14]',
    phases: [
      { phaseName: 'Phase 1: Compliance Audit & Hostinger Private VPS', scope: 'AES-256 encryption & private n8n node setup', timeline: '1 week', cost: 6500 },
      { phaseName: 'Phase 2: CRM & Portfolio Database Pipeline', scope: 'Real-time client reporting & automated alerts', timeline: '2 weeks', cost: 6000 },
      { phaseName: 'Phase 3: Managed Automation Retainer', scope: 'Priority incident response & monthly workflow additions', timeline: 'Monthly', cost: 5500 },
    ],
    createdAt: '2026-07-10',
  },
];

export const INITIAL_ACTIVITIES: Activity[] = [
  {
    id: 'act-801',
    leadId: 'l-101',
    entityName: 'Sydney Roofing Experts',
    employeeId: 'u-4',
    employeeName: 'Elena Rostova',
    type: 'CALL',
    title: 'Discovery Call with Dave Thompson',
    description: 'Discussed missed calls after 5 PM. Dave confirmed losing ~$15k in monthly roof repair jobs.',
    loggedAt: '2026-07-02T14:30:00Z',
  },
  {
    id: 'act-802',
    clientId: 'c-202',
    entityName: 'LA Dental Care Group',
    employeeId: 'u-2',
    employeeName: 'Alex Rivera',
    type: 'MEETING',
    title: 'Voice Bot Persona Review with Dr. Chen',
    description: 'Tested natural sounding female voice persona. Approved greeting script & cancellation protocol.',
    loggedAt: '2026-07-11T10:00:00Z',
  },
  {
    id: 'act-803',
    clientId: 'c-205',
    entityName: 'Apex Wealth Management AU',
    employeeId: 'u-1',
    employeeName: 'Sarah Jenkins',
    type: 'NOTE',
    title: 'Contract Sign-Off Confirmed',
    description: 'Received signed proposal from Harrison Vance. Allocated Marcus Vance as Lead Engineer.',
    loggedAt: '2026-07-14T16:15:00Z',
  },
];

export const INITIAL_TIMELOGS: TimeLog[] = [
  {
    id: 'tl-901',
    employeeId: 'u-2',
    employeeName: 'Alex Rivera',
    projectId: 'p-401',
    projectName: 'AI Voice Receptionist Rollout',
    clientId: 'c-202',
    clientName: 'LA Dental Care Group',
    hours: 3.5,
    billable: true,
    date: '2026-07-19',
    description: 'Configured Vapi streaming websockets and speech recognition thresholds.',
  },
  {
    id: 'tl-902',
    employeeId: 'u-4',
    employeeName: 'Elena Rostova',
    projectId: 'p-402',
    projectName: 'GHL Emergency Call Pipeline',
    clientId: 'c-201',
    clientName: 'Sydney Roofing Experts',
    hours: 3.0,
    billable: true,
    date: '2026-07-18',
    description: 'Built GHL snapshot triggers for automated SMS follow-up upon missed call.',
  },
];

export const INITIAL_AUDITLOGS: AuditLog[] = [
  {
    id: 'aud-1001',
    userName: 'Sarah Jenkins',
    userRole: 'ADMIN',
    action: 'LEAD_WON',
    entityType: 'Lead',
    details: 'Converted lead "Sydney Roofing Experts" to Active Client record c-201.',
    timestamp: '2026-07-05T09:12:00Z',
  },
  {
    id: 'aud-1002',
    userName: 'Elena Rostova',
    userRole: 'MEMBER',
    action: 'INVOICE_GENERATED',
    entityType: 'Invoice',
    details: 'Generated INV-2026-004 for Sydney Roofing Experts ($2,200).',
    timestamp: '2026-07-01T11:00:00Z',
  },
  {
    id: 'aud-1003',
    userName: 'Alex Rivera',
    userRole: 'MEMBER',
    action: 'PROJECT_UPDATE',
    entityType: 'Project',
    details: 'Updated status of "VIP Reservation Voice Agent" to COMPLETED.',
    timestamp: '2026-07-19T17:45:00Z',
  },
];

export const INITIAL_WEBHOOKS: WebhookLog[] = [
  {
    id: 'wh-1',
    source: 'GoHighLevel',
    payload: { event: 'contact_created', name: 'John Miller', phone: '+61 411 000 999', tags: ['Website Form', 'Sydney'] },
    receivedAt: '2026-07-21T08:12:00Z',
    status: 'PROCESSED',
  },
  {
    id: 'wh-2',
    source: 'Apollo.io',
    payload: { event: 'enrichment_complete', company: 'LA Dental Care Inc', revenue: '$3.5M', employees: 18 },
    receivedAt: '2026-07-21T07:45:00Z',
    status: 'PROCESSED',
  },
];
